### ISSUE TITLE
No such file or directory :  #include <proj.h>

### ISSUE THREAD

**Issue by iFence** [twpayne/go-proj#12]
When I run the program, the following problem occurs：
--------------------------------------------------------------------------------
go run src/main.go
# github.com/twpayne/go-proj/v10
In file included from ../../go/pkg/mod/github.com/twpayne/go-proj/v10@v10.1.1/context.go:4:0:
./go-proj.h:4:18: fatal error: proj.h: No such file or directory
 #include <proj.h>
                  ^
compilation terminated.
----------------------------------------------------------------------------
my go version is go1.19.13

**Comment by twpayne** [comment]
You must also install the PROJ development headers and libraries. These are typically in the package `libproj-dev` on Debian-like systems, `proj-devel` on RedHat-like systems, and `proj` in Homebrew.

Your Go version is also old and no longer supported. go-proj, like Go, only supports the current stable and old stable releases of Go, currently Go 1.20 and later.
